package de.zeus.ibmi.infrastructure.output;

import de.zeus.ibmi.transform.ColumnDefinition;
import de.zeus.ibmi.transform.QueryResult;
import de.zeus.ibmi.transform.RecordRow;

public final class HtmlOutputWriter extends AbstractStringOutputWriter {

  @Override
  public String formatName() {
    return "html";
  }

  @Override
  public String render(QueryResult result) {
    StringBuilder out = new StringBuilder();
    out.append(
        """
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <title>zeus-ibmi-extract-transform Export</title>
              <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
              <style>
                :root {
                  color-scheme: light dark;
                  --surface-bg: #f6f8fb;
                  --surface-card: #ffffff;
                  --surface-border: #d4dceb;
                  --text-main: #1f2937;
                  --text-muted: #5b6577;
                  --header-bg: #0d6efd;
                  --header-text: #ffffff;
                }
                @media (prefers-color-scheme: dark) {
                  :root {
                    --surface-bg: #0f141d;
                    --surface-card: #161f2c;
                    --surface-border: #2f3b50;
                    --text-main: #e6ecf8;
                    --text-muted: #a7b0c2;
                    --header-bg: #365fbe;
                    --header-text: #f7f9fd;
                  }
                }
                body {
                  margin: 0;
                  background: radial-gradient(circle at top right, #1d4ed811, transparent 48%), var(--surface-bg);
                  color: var(--text-main);
                  font-family: "Segoe UI", "Noto Sans", "Liberation Sans", sans-serif;
                }
                .export-wrap {
                  max-width: 1200px;
                  margin: 2rem auto;
                  padding: 0 1rem;
                }
                .export-card {
                  background: var(--surface-card);
                  border: 1px solid var(--surface-border);
                  border-radius: 0.9rem;
                  box-shadow: 0 12px 28px #00000014;
                  overflow: hidden;
                }
                .export-header {
                  padding: 1rem 1.25rem;
                  border-bottom: 1px solid var(--surface-border);
                }
                .export-title {
                  margin: 0;
                  font-size: 1.3rem;
                  font-weight: 600;
                }
                .export-subtitle {
                  margin: 0.35rem 0 0;
                  color: var(--text-muted);
                  font-size: 0.92rem;
                }
                .table-wrap {
                  padding: 0.9rem;
                }
                .table {
                  margin: 0;
                  border-color: var(--surface-border);
                }
                .table > :not(caption) > * > * {
                  color: var(--text-main);
                  background-color: transparent;
                  border-color: var(--surface-border);
                  vertical-align: top;
                  white-space: pre-wrap;
                  word-break: break-word;
                }
                .table thead th {
                  background: var(--header-bg);
                  color: var(--header-text);
                  font-weight: 600;
                  position: sticky;
                  top: 0;
                }
              </style>
            </head>
            <body>
            <main class="export-wrap">
              <section class="export-card">
                <header class="export-header">
                  <h1 class="export-title">IBM i / DB2 for i Query Export</h1>
                  <p class="export-subtitle">Generated by zeus-ibmi-extract-transform | Rows: """);
    out.append(" ").append(result.rowCount());
    out.append("</p>\n");
    out.append(
        """
                </header>
                <div class="table-wrap table-responsive">
                  <table class="table table-striped table-hover table-bordered align-middle">
                    <thead>
                      <tr>
            """);

    for (ColumnDefinition column : result.columns()) {
      out.append("            <th scope=\"col\" title=\"JDBC Type: ")
          .append(escapeHtml(column.jdbcTypeName()))
          .append("\">")
          .append(escapeHtml(column.name()))
          .append("</th>\n");
    }

    out.append(
        """
                      </tr>
                    </thead>
                    <tbody>
            """);

    for (RecordRow row : result.rows()) {
      out.append("          <tr>\n");
      for (ColumnDefinition column : result.columns()) {
        Object value = row.value(column.name());
        out.append("            <td>")
            .append(escapeHtml(value == null ? "" : String.valueOf(value)))
            .append("</td>\n");
      }
      out.append("          </tr>\n");
    }

    out.append(
        """
                    </tbody>
                  </table>
                </div>
              </section>
            </main>
            </body>
            </html>
            """);
    return out.toString();
  }

  private static String escapeHtml(String value) {
    if (value == null || value.isEmpty()) {
      return "";
    }
    StringBuilder escaped = new StringBuilder(value.length() + 16);
    for (int i = 0; i < value.length(); i++) {
      char c = value.charAt(i);
      switch (c) {
        case '&' -> escaped.append("&amp;");
        case '<' -> escaped.append("&lt;");
        case '>' -> escaped.append("&gt;");
        case '"' -> escaped.append("&quot;");
        case '\'' -> escaped.append("&#39;");
        default -> escaped.append(c);
      }
    }
    return escaped.toString();
  }
}
